uses: .woodpecker/deploy.yml
environment: be
with:
  component: be
  validate_command: echo "Validating be files..."
  deploy_image: alpine:3.19

params:
  - name: type
    type: select
    options:
      - fe
      - be
  - name: environment
    type: select
    options:
      - dev
      - prod
    default: dev
  - name: notify_slack
    type: boolean
    default: "false"

when:
  event: manual
  evaluate: type == "be"
