uses: .woodpecker/deploy.yml
environment: staging
with:
  component: app
  validate_command: echo "Push-triggered validation Ok la la"
  deploy_image: alpine:3.19

when:
  branch: feat/workflow
  event: push
